### DISCUSSION TITLE
Delay In Task Execution

### DISCUSSION THREAD

**Discussion by safaci2000** [hibiken/asynq#917] [Q&A] [answered]
I have a pretty simple setup right now.  

1. Single Redis node running in a docker compose stack.

```
  redis:
    image: redis:7.2.1
    healthcheck:
       test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
      - funcap-backend
    volumes:
      - redis_volume:/data

    ports:
      - "6379:6379"
    profiles:
      - app
```

I'm using Asynq to schedule tasks and I'm starting to see a delay in response.  The [UI](https://github.com/hibiken/asynqmon) is showing that the task is executing 'now', but it lingers for a good while.  My last run, I had 78 tasks scheduled at the same time and most of them didn't execute till 4-5 minutes after the expected time.

This is what I'm doing in code:

```go
func (w *worker) stopCapture() {
	asyncTask, err := newTaskSubmission(taskType, request, asynq.MaxRetry(MaxTaskRetry))
	if err != nil {
		log.Error().Err(err).Msg("Unable to create a new task")
		return 0, cancelNoOp, err
	}
	// Update task to DB
	startTime := time.Unix(scheduledTime, 0)


	info, err := w.client.Enqueue(asyncTask, asynq.ProcessAt(startTime))
	if err != nil {
		return 0, cancelNoOp, err
	}
	
}

func newTaskSubmission[T any](name string, request *T, opts ...asynq.Option) (*asynq.Task, error) {
	if request == nil {
		return nil, errors.New("invalid request received")
	}
	payload, err := json.Marshal(request)
	if err != nil {
		return nil, err
	}
	return asynq.NewTask(name, payload, opts...), nil
}	
```

I'm wondering if anyone else has run into this before?
