### ISSUE TITLE
[BUG] asynq client failed when use command `stats` 

### ISSUE THREAD

**Issue by duyhungtnn** [hibiken/asynq#309]
**Describe the bug**
- After connect asynq with our Redis server, run a command `asynq stats`. It take so long to complete and end up with 
```
ryan@ ~ asynq stats

Using config file: /Users/ryan/.asynq.yml

UNKNOWN: UNKNOWN: redis command error: MEMORY USAGE failed: redis: nil
```

**To Reproduce**
Steps to reproduce the behavior (Code snippets if applicable):
0. Setup redis with docker-compose 
```
version: '3.1'

services:
  redis:
    container_name: abc_redis
    image: redis:6.2.5-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - './data:/data'

networks:
  default:
    external:
      name: abc
```

1. Setup background processing ...
2. Enqueue tasks ...
3. See Error ...

**Expected behavior**
- Need to see the stats of the system

**Screenshots**
![Screen Shot 2021-08-07 at 11 07 54](https://user-images.githubusercontent.com/2597710/128587604-587a417d-cb33-4949-881b-791416c1d40d.png)

**Environment (please complete the following information):**
 - OS: [Ubuntu 18.4]
 - Version of `asynq` package [v0.18.2]

**Additional context**
- The worker and scheduler work as normal 
![Screen Shot 2021-08-07 at 11 20 15](https://user-images.githubusercontent.com/2597710/128587715-82bfc73d-fff7-4d7c-852f-8fa03dfae42f.png)

- The data on Redis is okay too
![Screen Shot 2021-08-07 at 11 19 05](https://user-images.githubusercontent.com/2597710/128587694-d1a9a7ea-3781-4e25-bdaa-089179a3f369.png)
